# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MPM.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main_Player_Menu(object):
    def setupUi(self, Main_Player_Menu):
        Main_Player_Menu.setObjectName("Main_Player_Menu")
        Main_Player_Menu.resize(644, 375)
        Main_Player_Menu.setMinimumSize(QtCore.QSize(644, 375))
        Main_Player_Menu.setMaximumSize(QtCore.QSize(644, 375))
        Main_Player_Menu.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/BlurBG.png);")
        self.label = QtWidgets.QLabel(Main_Player_Menu)
        self.label.setGeometry(QtCore.QRect(71, 10, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(25, 25, 25);\n"
"color: rgb(255, 255, 255);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);")
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setObjectName("label")
        self.groupBox1 = QtWidgets.QGroupBox(Main_Player_Menu)
        self.groupBox1.setGeometry(QtCore.QRect(7, 60, 120, 311))
        self.groupBox1.setAutoFillBackground(False)
        self.groupBox1.setStyleSheet("background-image: url(:/SPCTF Logo/PixelGrass1.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.groupBox1.setTitle("")
        self.groupBox1.setObjectName("groupBox1")
        self.pushButton1 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton1.setGeometry(QtCore.QRect(0, 0, 120, 311))
        self.pushButton1.setMinimumSize(QtCore.QSize(120, 311))
        self.pushButton1.setMaximumSize(QtCore.QSize(120, 311))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton1.setFont(font)
        self.pushButton1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton1.setAutoFillBackground(False)
        self.pushButton1.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/PixelGrass1.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton1.setText("")
        self.pushButton1.setCheckable(False)
        self.pushButton1.setAutoRepeat(False)
        self.pushButton1.setAutoDefault(False)
        self.pushButton1.setDefault(False)
        self.pushButton1.setObjectName("pushButton1")
        self.LV1_Label = QtWidgets.QLabel(self.groupBox1)
        self.LV1_Label.setEnabled(True)
        self.LV1_Label.setGeometry(QtCore.QRect(2, 60, 115, 31))
        self.LV1_Label.setMinimumSize(QtCore.QSize(115, 31))
        self.LV1_Label.setMaximumSize(QtCore.QSize(115, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LV1_Label.setFont(font)
        self.LV1_Label.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/color2.png);\n"
"color: rgb(0, 0, 0);\n"
"border-style: None;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"border-color: black;\n"
"padding: 0px;")
        self.LV1_Label.setTextFormat(QtCore.Qt.RichText)
        self.LV1_Label.setObjectName("LV1_Label")
        self.LV1_Text = QtWidgets.QLabel(self.groupBox1)
        self.LV1_Text.setGeometry(QtCore.QRect(2, 2, 115, 64))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LV1_Text.setFont(font)
        self.LV1_Text.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/PixelGrass1.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: None;\n"
"border-width: 0px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 0px;")
        self.LV1_Text.setObjectName("LV1_Text")
        self.TwistedThreads_Button = QtWidgets.QPushButton(self.groupBox1)
        self.TwistedThreads_Button.setEnabled(True)
        self.TwistedThreads_Button.setGeometry(QtCore.QRect(6, 110, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.TwistedThreads_Button.setFont(font)
        self.TwistedThreads_Button.setAutoFillBackground(False)
        self.TwistedThreads_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/TwistedThreads.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.TwistedThreads_Button.setText("")
        self.TwistedThreads_Button.setObjectName("TwistedThreads_Button")
        self.Julius_Button = QtWidgets.QPushButton(self.groupBox1)
        self.Julius_Button.setGeometry(QtCore.QRect(44, 157, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Julius_Button.setFont(font)
        self.Julius_Button.setAutoFillBackground(False)
        self.Julius_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/Julius.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.Julius_Button.setText("")
        self.Julius_Button.setObjectName("Julius_Button")
        self.FixME_Button = QtWidgets.QPushButton(self.groupBox1)
        self.FixME_Button.setGeometry(QtCore.QRect(6, 206, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.FixME_Button.setFont(font)
        self.FixME_Button.setAutoFillBackground(False)
        self.FixME_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/FixME.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.FixME_Button.setText("")
        self.FixME_Button.setObjectName("FixME_Button")
        self.Force_Me_Button = QtWidgets.QPushButton(self.groupBox1)
        self.Force_Me_Button.setGeometry(QtCore.QRect(44, 256, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Force_Me_Button.setFont(font)
        self.Force_Me_Button.setAutoFillBackground(False)
        self.Force_Me_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/Force Me!.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.Force_Me_Button.setText("")
        self.Force_Me_Button.setObjectName("Force_Me_Button")
        self.pushButton1.raise_()
        self.LV1_Text.raise_()
        self.LV1_Label.raise_()
        self.TwistedThreads_Button.raise_()
        self.Julius_Button.raise_()
        self.FixME_Button.raise_()
        self.Force_Me_Button.raise_()
        self.groupBox2 = QtWidgets.QGroupBox(Main_Player_Menu)
        self.groupBox2.setGeometry(QtCore.QRect(136, 60, 120, 311))
        self.groupBox2.setAutoFillBackground(False)
        self.groupBox2.setStyleSheet("background-image: url(:/SPCTF Logo/PixelGrass1.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.groupBox2.setTitle("")
        self.groupBox2.setObjectName("groupBox2")
        self.pushButton2 = QtWidgets.QPushButton(self.groupBox2)
        self.pushButton2.setGeometry(QtCore.QRect(0, 0, 120, 311))
        self.pushButton2.setMinimumSize(QtCore.QSize(120, 311))
        self.pushButton2.setMaximumSize(QtCore.QSize(120, 311))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton2.setFont(font)
        self.pushButton2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton2.setAutoFillBackground(False)
        self.pushButton2.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/PixelWaterfall1.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton2.setText("")
        self.pushButton2.setCheckable(False)
        self.pushButton2.setAutoRepeat(False)
        self.pushButton2.setAutoDefault(False)
        self.pushButton2.setDefault(False)
        self.pushButton2.setObjectName("pushButton2")
        self.LV2_Label = QtWidgets.QLabel(self.groupBox2)
        self.LV2_Label.setEnabled(True)
        self.LV2_Label.setGeometry(QtCore.QRect(2, 220, 115, 31))
        self.LV2_Label.setMinimumSize(QtCore.QSize(115, 31))
        self.LV2_Label.setMaximumSize(QtCore.QSize(115, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LV2_Label.setFont(font)
        self.LV2_Label.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/color2.png);\n"
"color: rgb(0, 0, 0);\n"
"border-style: None;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"border-color: black;\n"
"padding: 0px;")
        self.LV2_Label.setTextFormat(QtCore.Qt.RichText)
        self.LV2_Label.setObjectName("LV2_Label")
        self.LV2_Text = QtWidgets.QLabel(self.groupBox2)
        self.LV2_Text.setGeometry(QtCore.QRect(2, 245, 115, 65))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LV2_Text.setFont(font)
        self.LV2_Text.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/PixelWaterfall1.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: None;\n"
"border-width: 0px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 0px;")
        self.LV2_Text.setObjectName("LV2_Text")
        self.TM_Button = QtWidgets.QPushButton(self.groupBox2)
        self.TM_Button.setGeometry(QtCore.QRect(44, 163, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.TM_Button.setFont(font)
        self.TM_Button.setAutoFillBackground(False)
        self.TM_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/TM.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.TM_Button.setText("")
        self.TM_Button.setObjectName("TM_Button")
        self.Tight_Pixels_Button = QtWidgets.QPushButton(self.groupBox2)
        self.Tight_Pixels_Button.setGeometry(QtCore.QRect(4, 117, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Tight_Pixels_Button.setFont(font)
        self.Tight_Pixels_Button.setAutoFillBackground(False)
        self.Tight_Pixels_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/Tight Pixels.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.Tight_Pixels_Button.setText("")
        self.Tight_Pixels_Button.setObjectName("Tight_Pixels_Button")
        self.Suspicious_Program_Button = QtWidgets.QPushButton(self.groupBox2)
        self.Suspicious_Program_Button.setGeometry(QtCore.QRect(44, 70, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Suspicious_Program_Button.setFont(font)
        self.Suspicious_Program_Button.setAutoFillBackground(False)
        self.Suspicious_Program_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/Suspicious Program.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.Suspicious_Program_Button.setText("")
        self.Suspicious_Program_Button.setObjectName("Suspicious_Program_Button")
        self.Wrongdacted_Button = QtWidgets.QPushButton(self.groupBox2)
        self.Wrongdacted_Button.setGeometry(QtCore.QRect(4, 23, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Wrongdacted_Button.setFont(font)
        self.Wrongdacted_Button.setAutoFillBackground(False)
        self.Wrongdacted_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/Wrongdacted.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.Wrongdacted_Button.setText("")
        self.Wrongdacted_Button.setObjectName("Wrongdacted_Button")
        self.pushButton2.raise_()
        self.LV2_Text.raise_()
        self.LV2_Label.raise_()
        self.TM_Button.raise_()
        self.Tight_Pixels_Button.raise_()
        self.Suspicious_Program_Button.raise_()
        self.Wrongdacted_Button.raise_()
        self.groupBox3 = QtWidgets.QGroupBox(Main_Player_Menu)
        self.groupBox3.setGeometry(QtCore.QRect(263, 60, 120, 311))
        self.groupBox3.setAutoFillBackground(False)
        self.groupBox3.setStyleSheet("background-image: url(:/SPCTF Logo/PixelGrass1.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.groupBox3.setTitle("")
        self.groupBox3.setObjectName("groupBox3")
        self.pushButton3 = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton3.setGeometry(QtCore.QRect(0, 0, 120, 311))
        self.pushButton3.setMinimumSize(QtCore.QSize(120, 311))
        self.pushButton3.setMaximumSize(QtCore.QSize(120, 311))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton3.setFont(font)
        self.pushButton3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton3.setAutoFillBackground(False)
        self.pushButton3.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/PixelMountain1.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton3.setText("")
        self.pushButton3.setCheckable(False)
        self.pushButton3.setAutoRepeat(False)
        self.pushButton3.setAutoDefault(False)
        self.pushButton3.setDefault(False)
        self.pushButton3.setObjectName("pushButton3")
        self.LV3_Label = QtWidgets.QLabel(self.groupBox3)
        self.LV3_Label.setEnabled(True)
        self.LV3_Label.setGeometry(QtCore.QRect(2, 60, 115, 31))
        self.LV3_Label.setMinimumSize(QtCore.QSize(115, 31))
        self.LV3_Label.setMaximumSize(QtCore.QSize(115, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LV3_Label.setFont(font)
        self.LV3_Label.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/color2.png);\n"
"color: rgb(0, 0, 0);\n"
"border-style: None;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"border-color: black;\n"
"padding: 0px;")
        self.LV3_Label.setTextFormat(QtCore.Qt.RichText)
        self.LV3_Label.setObjectName("LV3_Label")
        self.LV3_Text = QtWidgets.QLabel(self.groupBox3)
        self.LV3_Text.setGeometry(QtCore.QRect(2, 2, 115, 64))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LV3_Text.setFont(font)
        self.LV3_Text.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/PixelMountain1.png);\n"
"color: rgb(0, 0, 0);\n"
"border-style: None;\n"
"border-width: 0px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 0px;")
        self.LV3_Text.setObjectName("LV3_Text")
        self.Lieda_Pro_Button = QtWidgets.QPushButton(self.groupBox3)
        self.Lieda_Pro_Button.setEnabled(True)
        self.Lieda_Pro_Button.setGeometry(QtCore.QRect(6, 206, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Lieda_Pro_Button.setFont(font)
        self.Lieda_Pro_Button.setAutoFillBackground(False)
        self.Lieda_Pro_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/LiedaPro.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.Lieda_Pro_Button.setText("")
        self.Lieda_Pro_Button.setObjectName("Lieda_Pro_Button")
        self.Maze_Button = QtWidgets.QPushButton(self.groupBox3)
        self.Maze_Button.setGeometry(QtCore.QRect(44, 256, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Maze_Button.setFont(font)
        self.Maze_Button.setAutoFillBackground(False)
        self.Maze_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/Maze.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.Maze_Button.setText("")
        self.Maze_Button.setObjectName("Maze_Button")
        self.RDP_Button = QtWidgets.QPushButton(self.groupBox3)
        self.RDP_Button.setGeometry(QtCore.QRect(44, 157, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.RDP_Button.setFont(font)
        self.RDP_Button.setAutoFillBackground(False)
        self.RDP_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/RDP.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.RDP_Button.setText("")
        self.RDP_Button.setObjectName("RDP_Button")
        self.Eighty_Button = QtWidgets.QPushButton(self.groupBox3)
        self.Eighty_Button.setGeometry(QtCore.QRect(6, 110, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Eighty_Button.setFont(font)
        self.Eighty_Button.setAutoFillBackground(False)
        self.Eighty_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/8086.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 5px;")
        self.Eighty_Button.setText("")
        self.Eighty_Button.setObjectName("Eighty_Button")
        self.pushButton3.raise_()
        self.LV3_Text.raise_()
        self.LV3_Label.raise_()
        self.Lieda_Pro_Button.raise_()
        self.Maze_Button.raise_()
        self.RDP_Button.raise_()
        self.Eighty_Button.raise_()
        self.groupBox4 = QtWidgets.QGroupBox(Main_Player_Menu)
        self.groupBox4.setGeometry(QtCore.QRect(389, 60, 120, 311))
        self.groupBox4.setAutoFillBackground(False)
        self.groupBox4.setStyleSheet("background-image: url(:/SPCTF Logo/PixelGrass1.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.groupBox4.setTitle("")
        self.groupBox4.setObjectName("groupBox4")
        self.pushButton4 = QtWidgets.QPushButton(self.groupBox4)
        self.pushButton4.setGeometry(QtCore.QRect(0, 0, 120, 311))
        self.pushButton4.setMinimumSize(QtCore.QSize(120, 311))
        self.pushButton4.setMaximumSize(QtCore.QSize(120, 311))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton4.setFont(font)
        self.pushButton4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton4.setAutoFillBackground(False)
        self.pushButton4.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/PixelVolcano.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton4.setText("")
        self.pushButton4.setCheckable(False)
        self.pushButton4.setAutoRepeat(False)
        self.pushButton4.setAutoDefault(False)
        self.pushButton4.setDefault(False)
        self.pushButton4.setObjectName("pushButton4")
        self.LV4_Label = QtWidgets.QLabel(self.groupBox4)
        self.LV4_Label.setEnabled(True)
        self.LV4_Label.setGeometry(QtCore.QRect(2, 220, 115, 31))
        self.LV4_Label.setMinimumSize(QtCore.QSize(115, 31))
        self.LV4_Label.setMaximumSize(QtCore.QSize(115, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LV4_Label.setFont(font)
        self.LV4_Label.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/color2.png);\n"
"color: rgb(0, 0, 0);\n"
"border-style: None;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"border-color: black;\n"
"padding: 0px;")
        self.LV4_Label.setTextFormat(QtCore.Qt.RichText)
        self.LV4_Label.setObjectName("LV4_Label")
        self.LV4_Text = QtWidgets.QLabel(self.groupBox4)
        self.LV4_Text.setGeometry(QtCore.QRect(2, 245, 115, 65))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LV4_Text.setFont(font)
        self.LV4_Text.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/PixelVolcano.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: None;\n"
"border-width: 0px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 0px;")
        self.LV4_Text.setObjectName("LV4_Text")
        self.Dictionary_Button = QtWidgets.QPushButton(self.groupBox4)
        self.Dictionary_Button.setGeometry(QtCore.QRect(25, 53, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Dictionary_Button.setFont(font)
        self.Dictionary_Button.setAutoFillBackground(False)
        self.Dictionary_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/Dictionary.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.Dictionary_Button.setText("")
        self.Dictionary_Button.setObjectName("Dictionary_Button")
        self.Memory_Button = QtWidgets.QPushButton(self.groupBox4)
        self.Memory_Button.setGeometry(QtCore.QRect(25, 143, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Memory_Button.setFont(font)
        self.Memory_Button.setAutoFillBackground(False)
        self.Memory_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/EEPROM.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.Memory_Button.setText("")
        self.Memory_Button.setObjectName("Memory_Button")
        self.pushButton4.raise_()
        self.LV4_Text.raise_()
        self.LV4_Label.raise_()
        self.Dictionary_Button.raise_()
        self.Memory_Button.raise_()
        self.groupBox5 = QtWidgets.QGroupBox(Main_Player_Menu)
        self.groupBox5.setGeometry(QtCore.QRect(516, 60, 120, 311))
        self.groupBox5.setAutoFillBackground(False)
        self.groupBox5.setStyleSheet("background-image: url(:/SPCTF Logo/PixelGrass1.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.groupBox5.setTitle("")
        self.groupBox5.setObjectName("groupBox5")
        self.pushButton5 = QtWidgets.QPushButton(self.groupBox5)
        self.pushButton5.setGeometry(QtCore.QRect(0, 0, 120, 311))
        self.pushButton5.setMinimumSize(QtCore.QSize(120, 311))
        self.pushButton5.setMaximumSize(QtCore.QSize(120, 311))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton5.setFont(font)
        self.pushButton5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton5.setAutoFillBackground(False)
        self.pushButton5.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/PixelSpace1.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton5.setText("")
        self.pushButton5.setCheckable(False)
        self.pushButton5.setAutoRepeat(False)
        self.pushButton5.setAutoDefault(False)
        self.pushButton5.setDefault(False)
        self.pushButton5.setObjectName("pushButton5")
        self.LV5_Label = QtWidgets.QLabel(self.groupBox5)
        self.LV5_Label.setEnabled(True)
        self.LV5_Label.setGeometry(QtCore.QRect(2, 60, 115, 31))
        self.LV5_Label.setMinimumSize(QtCore.QSize(115, 31))
        self.LV5_Label.setMaximumSize(QtCore.QSize(115, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LV5_Label.setFont(font)
        self.LV5_Label.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/color2.png);\n"
"color: rgb(0, 0, 0);\n"
"border-style: None;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"border-color: black;\n"
"padding: 0px;")
        self.LV5_Label.setTextFormat(QtCore.Qt.RichText)
        self.LV5_Label.setObjectName("LV5_Label")
        self.LV5_Text = QtWidgets.QLabel(self.groupBox5)
        self.LV5_Text.setGeometry(QtCore.QRect(2, 2, 115, 64))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LV5_Text.setFont(font)
        self.LV5_Text.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/PixelSpace1.png);\n"
"color: rgb(255, 255, 255);\n"
"border-style: None;\n"
"border-width: 0px;\n"
"border-radius: 11px;\n"
"border-color: black;\n"
"padding: 0px;")
        self.LV5_Text.setObjectName("LV5_Text")
        self.Dark_Mode_Button = QtWidgets.QPushButton(self.groupBox5)
        self.Dark_Mode_Button.setGeometry(QtCore.QRect(25, 135, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Dark_Mode_Button.setFont(font)
        self.Dark_Mode_Button.setAutoFillBackground(False)
        self.Dark_Mode_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/Dark Mode.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;")
        self.Dark_Mode_Button.setText("")
        self.Dark_Mode_Button.setObjectName("Dark_Mode_Button")
        self.RSA_Button = QtWidgets.QPushButton(self.groupBox5)
        self.RSA_Button.setGeometry(QtCore.QRect(25, 230, 71, 36))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.RSA_Button.setFont(font)
        self.RSA_Button.setAutoFillBackground(False)
        self.RSA_Button.setStyleSheet("image: url(:/SPCTF Logo/RAW IMG/RSA.png);\n"
"background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 9px;")
        self.RSA_Button.setText("")
        self.RSA_Button.setObjectName("RSA_Button")
        self.pushButton5.raise_()
        self.LV5_Text.raise_()
        self.LV5_Label.raise_()
        self.Dark_Mode_Button.raise_()
        self.RSA_Button.raise_()
        self.BackButton = QtWidgets.QPushButton(Main_Player_Menu)
        self.BackButton.setGeometry(QtCore.QRect(5, 12, 61, 36))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.BackButton.setFont(font)
        self.BackButton.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"image: url(:/SPCTF Logo/RAW IMG/LeftArrow.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;\n"
"color: rgb(255, 255, 255);")
        self.BackButton.setText("")
        self.BackButton.setObjectName("BackButton")
        self.ForwardButton = QtWidgets.QPushButton(Main_Player_Menu)
        self.ForwardButton.setGeometry(QtCore.QRect(577, 12, 61, 36))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.ForwardButton.setFont(font)
        self.ForwardButton.setStyleSheet("background-image: url(:/SPCTF Logo/RAW IMG/color.png);\n"
"image: url(:/SPCTF Logo/RAW IMG/RightArrow.png);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 11px;\n"
"border-color: white;\n"
"padding: 3px;\n"
"color: rgb(255, 255, 255);")
        self.ForwardButton.setText("")
        self.ForwardButton.setObjectName("ForwardButton")
        self.label.raise_()
        self.groupBox1.raise_()
        self.groupBox2.raise_()
        self.groupBox3.raise_()
        self.groupBox4.raise_()
        self.groupBox5.raise_()
        self.ForwardButton.raise_()
        self.BackButton.raise_()

        self.retranslateUi(Main_Player_Menu)
        QtCore.QMetaObject.connectSlotsByName(Main_Player_Menu)

    def retranslateUi(self, Main_Player_Menu):
        _translate = QtCore.QCoreApplication.translate
        Main_Player_Menu.setWindowTitle(_translate("Main_Player_Menu", "SPCTF"))
        self.label.setText(_translate("Main_Player_Menu", "<html><head/><body><p align=\"center\">Points: XXX</p></body></html>"))
        self.LV1_Label.setText(_translate("Main_Player_Menu", "<html><head/><body><p align=\"center\">Entry Point</p></body></html>"))
        self.LV1_Text.setText(_translate("Main_Player_Menu", "<html><head/><body><p align=\"center\">LV 1</p></body></html>"))
        self.LV2_Label.setText(_translate("Main_Player_Menu", "<html><head/><body><p align=\"center\">Mystic</p></body></html>"))
        self.LV2_Text.setText(_translate("Main_Player_Menu", "<html><head/><body><p align=\"center\">LV 2</p></body></html>"))
        self.LV3_Label.setText(_translate("Main_Player_Menu", "<html><head/><body><p align=\"center\">Struggle</p></body></html>"))
        self.LV3_Text.setText(_translate("Main_Player_Menu", "<html><head/><body><p align=\"center\">LV 3</p></body></html>"))
        self.LV4_Label.setText(_translate("Main_Player_Menu", "<html><head/><body><p align=\"center\">Cathedral</p></body></html>"))
        self.LV4_Text.setText(_translate("Main_Player_Menu", "<html><head/><body><p align=\"center\">LV 4</p></body></html>"))
        self.LV5_Label.setText(_translate("Main_Player_Menu", "<html><head/><body><p align=\"center\">Limitless</p></body></html>"))
        self.LV5_Text.setText(_translate("Main_Player_Menu", "<html><head/><body><p align=\"center\">LV 5</p></body></html>"))
